action_id: trunk-upgrade-available
date: 2023-10-07 09:19:21
run: trunk upgrade --notify --allow-daemon-restart=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 127
  out: ""
  err: "trunk-upgrade-available: line 1: trunk: command not found\n"
timestamp: 1696670361
full_timestamp:
  nanos: 748586000
  seconds: 1696670361
trunk_version: 1.3.2
